### PR TITLE
updateOutdatedPackages function & SolidJS Support

### PR DESCRIPTION
**Pull request by OrJDev**
updateOutdatedPackages - will update any package that doesn't include proxy in its version and startsWith @trpc/

### SolidJS - Before
```ts
  const response = trpc.createQuery(() => [
    "example.test",
    { name: "example" },
  ]);
  const mutationExample = trpc.createMutation(() => "example.mTest");
```

### SolidJS - After
```ts
  const response = trpc.example.test.useQuery({ name: "example" });
  const mutationExample = trpc.example.mTest.useMutation();
```

### CODE REVIEW

**Comment by sachinraja** [comment]
I wish you had opened an issue before doing all of this so we could've discussed it first.
A few questions though:

Is `solid-trpc` being used enough to justify including it here?
How does the install work when you're using any other package manager or setup (yarn, monorepo, etc.)?

**Comment by OrJDev** [comment]
> I wish you had opened an issue before doing all of this so we could've discussed it first.
> 
> Two questions though:
> 
> 
> 
> Is `solid-trpc` being used enough to justify including it here?
> 
> How does the install work when you're using any other package manager or setup (yarn, monorepo, etc.)?
> 
> 
> 
> Thanks!

Solid trpc is very new as tanstack only released solid query in the latest weeks, yet its the only package that allows you to use trpc hooks in solid.

And the install works using npm but it can also support pnpm and yarn if you want to.

**Comment by sachinraja** [comment]
> Solid trpc is very new as tanstack only released solid query in the latest weeks, yet its the only package that allows you to use trpc hooks in solid.

Sure, but that means it should be easy enough for people to update themselves right? They can still use this codemod for their server router.

> And the install works using npm but it can also support pnpm and yarn if you want to.
Update: now it supports yarn, npm and pnpm using the preferred-pm npm package.

I didn't mean for it to be a feature request, just a question. Updating versions is really not something I want to do as a part of this codemod. The goal of the codemod is not to be a complete solution that you just run and it works out of the box, but rather something that you run to do some straightforward changes for you.

**Comment by OrJDev** [comment]
> > Solid trpc is very new as tanstack only released solid query in the latest weeks, yet its the only package that allows you to use trpc hooks in solid.
> 
> 
> 
> Sure, but that means it should be easy enough for people to update themselves right? They can still use this codemod for their server router.
> 
> 
> 
> > And the install works using npm but it can also support pnpm and yarn if you want to.
> 
> Update: now it supports yarn, npm and pnpm using the preferred-pm npm package.
> 
> 
> 
> I didn't mean for it to be a feature request, just a question. Updating versions is really not something I want to do as a part of this codemod. The goal of the codemod is not to be a complete solution that you just run and it works out of the box, but rather something that you run to do some straightforward changes for you.

Yes they can update themselves but they can also update themselves react easily, its just a nice feature to have because no matter who makes a trpc package for solidjs its going to have the same syntax as mine, as tanstack solid query requires the key and input to be a solid accessor (callback) so:
React - useQuery([key, args])
becomes
Solid - createQuery(()=> [key, args])

**Comment by sachinraja** [comment]
> Yes they can update themselves but they can also update themselves react easily

There's a lot of demand for a React codemod just going by npm downloads. Many apps are already using it in production and have a ton of queries and mutations to update.

I don't really want to support Solid here, this codemod is only for `@trpc/*` packages. Anything else should probably be done in a separate codemod, unless there's a lot of demand for it.

**Comment by OrJDev** [comment]
> > Yes they can update themselves but they can also update themselves react easily
> 
> There's a lot of demand for a React codemod just going by npm downloads. Many apps are already using it in production and have a ton of queries and mutations to update.
> 
> I don't really want to support Solid here, this codemod is only for `@trpc/*` packages. Anything else should probably be done in a separate codemod, unless there's a lot of demand for it.

i understand, im not trying to force u to accept my changes i was bored so i made it and feel free to use it.

**Comment by sachinraja** [comment]
Thanks, will close this then. I appreciate the effort put into this though.

**Pull request closed without merging**
